config/routes.rb
Rails.application.routes.draw do
  resources :media_files
  get 'media_files/stage/:id' => 'media_files#stage', as: 'stage_media_file', :constraints => { :id => /.*/ }

end

app/models/media_file.rb
class MediaFile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/media_files_controller.rb
class MediaFilesController < ApplicationController
  before_action :set_media_file, only: [:show, :edit, :update, :destroy, :stage]

  # GET /media_files
  # GET /media_files.json
  def index
    @media_files = MediaFile.all
  end

  # GET /media_files/1
  # GET /media_files/1.json
  def show
    @store_resp = RestClient.get 'http://localhost:3000/storage_api/stores/' + @media_file.store + '/media_files/' + @media_file.name
    @cache_resp = RestClient.get 'http://localhost:3000/storage_api/caches/' + @media_file.cache +  '/cache_files/' + @media_file.name
  end

  # GET /media_files/new
  def new
    @media_file = MediaFile.new
  end

  # GET /media_files/1/edit
  def edit
  end

  # POST /media_files
  # POST /media_files.json
  def create
    @media_file = MediaFile.new(media_file_params)

    respond_to do |format|
      if @media_file.save
        format.html { redirect_to @media_file, notice: 'Media file was successfully created.' }
        format.json { render :show, status: :created, location: @media_file }
      else
        format.html { render :new }
        format.json { render json: @media_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def stage
    @store_resp = RestClient.post 'http://localhost:3000/storage_api/jobs/' + @media_file.cache + '/' + @media_file.name, :type => 'stage'
    redirect_to @media_file, notice: 'A job to stage this media file has been initiated.'
  end

  # PATCH/PUT /media_files/1
  # PATCH/PUT /media_files/1.json
  def update
    respond_to do |format|
      if @media_file.update(media_file_params)
        format.html { redirect_to @media_file, notice: 'Media file was successfully updated.' }
        format.json { render :show, status: :ok, location: @media_file }
      else
        format.html { render :edit }
        format.json { render json: @media_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_files/1
  # DELETE /media_files/1.json
  def destroy
    @media_file.destroy
    respond_to do |format|
      format.html { redirect_to media_files_url, notice: 'Media file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_file
      @media_file = MediaFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_file_params
      params.require(:media_file).permit(:name, :store, :cache, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_files_helper.rb
module MediaFilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Async UI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/media_files/_form.html.erb
<%= form_for(@media_file) do |f| %>
  <% if @media_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@media_file.errors.count, "error") %> prohibited this media_file from being saved:</h2>

      <ul>
      <% @media_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :store %><br>
    <%= f.text_field :store %>
  </div>
  <div class="field">
    <%= f.label :cache %><br>
    <%= f.text_field :cache %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/media_files/edit.html.erb
<h1>Editing Media File</h1>

<%= render 'form' %>

<%= link_to 'Show', @media_file %> |
<%= link_to 'Back', media_files_path %>

app/views/media_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Media Files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Store</th>
      <th>Cache</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media_files.each do |media_file| %>
      <tr>
        <td><%= media_file.name %></td>
        <td><%= media_file.store %></td>
        <td><%= media_file.cache %></td>
        <td><%= media_file.description %></td>
        <td><%= link_to 'Show', media_file %></td>
        <td><%= link_to 'Edit', edit_media_file_path(media_file) %></td>
        <td><%= link_to 'Destroy', media_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Media file', new_media_file_path %>

app/views/media_files/new.html.erb
<h1>New Media File</h1>

<%= render 'form' %>

<%= link_to 'Back', media_files_path %>

app/views/media_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @media_file.name %>
</p>

<p>
  <strong>Store:</strong>
  <%= @media_file.store %>
</p>

<p>
  <strong>Cache:</strong>
  <%= @media_file.cache %>
</p>

<p>
  <strong>Description:</strong>
  <%= @media_file.description %>
</p>

<p>
  <strong>Size(M):</strong>
  <%= JSON.parse(@store_resp)['size'] %>
</p>

<p>
  <strong>Checksum:</strong>
  <%= JSON.parse(@store_resp)['checksum'] %>
</p>

<p>
  <strong>
    <% if JSON.parse(@cache_resp)['status'] == 'staged'%>
      File available in cache:
      <%= link_to 'Download', 'http://localhost:3000' + JSON.parse(@cache_resp)['url'] %>
    <% elsif JSON.parse(@cache_resp)['status'] == 'staging'%>
      File staging to cache...
    <% else %>
      File not in cache |
      <%= link_to 'Stage file for download', stage_media_file_path %>
    <% end %>
  </strong>
</p>


<%= link_to 'Edit', edit_media_file_path(@media_file) %> |
<%= link_to 'Back', media_files_path %>